### ISSUE TITLE
Could you add some additional functions?

### ISSUE THREAD

**Issue by subminu** [Junyoung-Shin-22/timeout#1]
I think, there are some possible ways that can be manipulated, such as finding existing a voting message and switching the bot to meet the condition to timeout some other suddenly. Your bot need to also manage the existing messages that the bot wrote. Here are a couple of functions that I suggest for solving the problem that I mentioned.

1. Voting time for that vote. After the voting time, it should be deleted.
2. (opt) Even if the voting ends, since the vote met the condition, it should delete the voting message.

**Comment by Junyoung-Shin-22** [comment]
Thank you for your feedback! Suggested features will be added to the 0.1.2 update.
